### ISSUE TITLE
on helm upgrade, DB secrets are regenerated and connection to mysql is lost

### ISSUE THREAD

**Issue by malvex** [kubic-project/caasp-services#47]
Reproduction steps:
helm install portus --name portus
helm upgrade portus portus

DB secrets will get generated, but not updated in mariadb

**Comment by ArcticSnowman** [comment]
You need to set various passwords explicitly in your values.yaml, so that it's not regenerated.  

You will need to purge the install and wipe out the MariaDB storage and re-install.

The follow passwords need to be set
```
portus:
   password:

mariadb:
  rootUser:
    password:
  db:
     password:

```

I've started using https://github.com/futuresimple/helm-secrets to encode the password values.
