### ISSUE TITLE
[HELM CHART]  protus-secret.yaml template expects bind_pwd instead password for ldap config

### ISSUE THREAD

**Issue by ArcticSnowman** [kubic-project/caasp-services#48]
protus-secret.yaml template expects bind_pwd instead password for ldap config

`portus-secret.yaml`
```
  {{- if .Values.portus.config.ldap.authentication.enabled }}
  PORTUS_LDAP_AUTHENTICATION_PASSWORD: {{ .Values.portus.config.ldap.authentication.bind_pwd | b64enc | quote }}
  {{- end }}
```

`values.yaml`
```
      # LDAP credentials used to search for a user.
      authentication:
        enabled: true
        bind_dn: ""
        password: ""

```
