### ISSUE TITLE
Helm chart on kubernetes with nginx ingress controller does not work.

### ISSUE THREAD

**Issue by arkachatterjee** [kubic-project/caasp-services#55]
```
## Default values for Portus Helm Chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## Default values for Portus
##
portus:
  replicas: 1

  ## Image configuration.
  ##
  image:
    repository: "opensuse/portus"
    tag: "2.3"
    pullPolicy: "IfNotPresent"

  ## Service configuration.
  ##
  service:
    port: "3000"

  ## Resource configuration.
  ##
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"

  ## Portus database configuration.
  dbAdapter: "mysql2"

  ## only set db values if using existing database deployment
  ##
  # dbHost
  # dbDatabase:
  # dbUsername:
  # dbPassword:

  ## Defaults to a random 10-character alphanumeric string if not set
  ##
  # password:

  ## Defaults to a random 10-character alphanumeric string if not set
  ## Password used for mariadb connection
  # productionPassword: not-a-secure-password

  ## Defaults to a random 128-character alphanumeric string if not set
  ##
  # secretKeyBase:

  env:
    ## http://port.us.org/docs/debugging.html
    ## The available log levels are: debug, info, warn, error, fatal and unknown
    log_level: info

  ## config
  ##
  config:
    email:
      from: "portus@example.com"
      name: "Portus"
      reply_to: "no-reply@example.com"
      smtp:
        enabled: false
        address: smtp.example.com
        port: 587
        domain: example.com
        username: username@example.com
        password: not-a-password
    gravatar: true  # If enabled, then the profile picture will be picked from the Gravatar
    delete: true  # Allow admins and owners to delete images and tags

    ## LDAP support. If enabled, then only users of the specified LDAP server will
    ## be able to use Portus. Take a look at the documentation of LDAP support in our
    ## online docs: http://port.us.org/features/2_LDAP-support.html.
    ldap:
      enabled: false
      url:
      port:

      # Available options: "plain", "simple_tls" and "starttls". The default is
      # "plain", the recommended is "starttls".
      method: plain
      # The base where users are located (e.g. "ou=users,dc=example,dc=com").
      base:
      # User filter (e.g. "mail=george*").
      filter:
      # The LDAP attribute where to search for username. The default is 'uid'.
      uid:
      # LDAP credentials used to search for a user.
      authentication:
        enabled: false
        bind_dn:
        password:

      # Portus needs an email for each user, but there's no standard way to get
      # that from LDAP servers. You can tell Portus how to get the email from users
      # registered in the LDAP server with this configurable value. There are three
      # possibilities:
      #
      #   - disabled: this is the default value. It means that Portus won't do a
      #     thing when registering LDAP users (users will be redirected to their
      #     profile page until they setup an email account).
      #   - enabled where "attr" is empty: for this you need "ldap.base" to have
      #     some value. In this case, the hostname will be guessed from the domain
      #     component of the provided base string. For example, for the dn:
      #     "ou=users,dc=example,dc=com", and a user name "user", the resulting
      #     email is "user@example.com".
      #   - enabled where "attr" is not empty: with this you specify the attribute
      #     inside a LDIF record where the email is set.
      #
      # If something goes wrong when trying to guess the email, then it just falls
      # back to the default behavior (empty email).
      guess_email:
        enabled: false
        attr:

    first_user_admin: true # First user signing up will be admin
    signup: true  # If enabled, then users can signup with the signup form
    display_name: false  # Allow users to have different display names on the web site
    user_permission:
      change_visibility: true  # Allow users to change the visibility or their personal namespace
      create_team: true # Allow users to create teams
      manage_team: true  # Allow users to create/modify teams if they are an owner of it
      create_namespace: true # Allow users to create namespaces
      manage_namespace: true  # Allow users to create/modify namespaces if they are an owner of it

    oauth:
      # If enabled, users can authenticate with their Google Account.
      # Callback url: <host>/users/auth/google_oauth2/callback
      google_oauth2:
        enabled: false
        id:
        secret:
        domain:
        options:
          hd:

      # OpenID authentication support. If enabled, then users can authenticate with OpenID/Connect
      # Callback url: <host>/users/auth/open_id/callback
      open_id:
        enabled: false
        identifier:
        domain:

      # Github authentication support.
      # Callback url: <host>/users/auth/github/callback
      github:
        enabled: false
        client_id:
        client_secret:
        organization:
        team:
        domain:

      # Gitlab authentication support.
      # Callback url: <host>/users/auth/gitlab/callback
      gitlab:
        enabled: false
        application_id:
        secret:
        group:
        domain:
        server:

      # Bitbucket authentication support. Need permission to read email.
      # Callback url: <host>/users/auth/bitbucket/callback
      bitbucket:
        enabled: false
        key:
        secret:
        domain:
        options:
          team:

    security:
      clair:
        server: "" # This is only guaranteed to work for v2.0.x releases of Clair
        health_port: 6061 # Port being used by Clair to report its status
      zypper:
        server: "" #  support for this is experimental since this functionality has not been merged into master yet in zypper-docker
    anonymous_browsing: true # Allow anonymous (non-logged-in) users to explore the images available in your Docker Registry

  ## TLS configuration
  ## the internal host names of the portus, registry and nginx service must be covered by the key/cert in order for TLS to work properly
  ##
  tls:
    enabled: false

    ## must include key if using tls
    ##
    # key:

    ## must include certificate if using tls
    ##
    # cert:

  ## background processing
  ##
  background:
    enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "300m"

## Default values for Docker Registry.
##
registry:
  replicas: 1
  mountPath: "/storage"

  ## persistence configuration.
  ##
  persistence:
    enabled: true
    accessMode: "ReadWriteOnce"
    size: "10Gi"
    storageClass: do-block-storage

  ## image configuration.
  # #
  image:
    repository: "library/registry"
    tag: "2.5.2"
    pullPolicy: "IfNotPresent"

  ## Service configuration.
  ##
  service:
    port: "5000"
    debugPort: "5001"

  ## Resource configuration.
  ##
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"

## Default values for Nginx.
##
nginx:
  replicas: 1

  ## image configuration.
  ##
  image:
    repository: "library/nginx"
    tag: "alpine"
    pullPolicy: "IfNotPresent"

  service:
    type: "ClusterIP"
    port: 80
  host: docker-hub.xxxx.com
  ## ingress configuration.
  ##
  ingress:
    enabled: true
    host: docker-hub.xxxx.com
    tls:
      enabled: true
      secretName: xxxx-tls-certificate

  ## Resource configuration.
  ##
  # resources:
  #   requests:
  #     memory: "512Mi"
  #     cpu: "300m"

## Default values for Mariadb.
##
mariadb:
  ## Use Mariadb chart dependency
  ## Set to false if using your own Mariadb
  ##
  enabled: true

  ## persistence configuration.
  ##
  persistence:
    enabled: true
    storageClass: do-block-storage
    accessMode: "ReadWriteOnce"
    size: "10Gi"

  ## Configuration values for Mariadb.
  ## must match Portus database values.
  ##
  mariadbUser: "portus"
  mariadbDatabase: "P0rtu5"
```

This is my values.yaml

________

helm install --name xxxx-registry --namespace registry portus
NAME:   xxxx-registry
LAST DEPLOYED: Wed Jan  2 23:12:46 2019
NAMESPACE: registry
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME                                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
xxxx-registry-mariadb          1        1        1           0          1s
xxxx-registry-portus-nginx     1        1        1           0          1s
xxxx-registry-portus           1        1        1           0          1s
xxxx-registry-portus-registry  1        1        1           0          1s

==> v1beta1/Ingress
NAME                             HOSTS                     ADDRESS  PORTS  AGE
xxxx-registry-portus-nginx  docker-hub.xxxx.com  80, 443  1s

==> v1/Pod(related)
NAME                                                 READY  STATUS             RESTARTS  AGE
xxxx-registry-mariadb-6db88df69f-cndq2          0/1    Pending            0         1s
xxxx-registry-portus-nginx-5b5c657cdb-wpfhs     0/1    ContainerCreating  0         1s
xxxx-registry-portus-69bbc54c9b-kglg4           0/2    ContainerCreating  0         1s
xxxx-registry-portus-registry-546bbb575d-sdtbn  0/1    Pending            0         1s

==> v1/Secret
NAME                        TYPE    DATA  AGE
xxxx-registry-mariadb  Opaque  2     2s
xxxx-registry-portus   Opaque  2     2s

==> v1/ConfigMap
NAME                                DATA  AGE
xxxx-registry-mariadb          1     2s
xxxx-registry-mariadb-tests    1     2s
xxxx-registry-portus-nginx     1     2s
xxxx-registry-portus           2     2s
xxxx-registry-portus-registry  4     2s

==> v1/PersistentVolumeClaim
NAME                                STATUS   VOLUME            CAPACITY  ACCESS MODES  STORAGECLASS  AGE
xxxx-registry-mariadb          Pending  do-block-storage  2s
xxxx-registry-portus-registry  Pending  do-block-storage  2s

==> v1/Service
NAME                                TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)            AGE
xxxx-registry-mariadb          ClusterIP  10.245.151.210  <none>       3306/TCP           1s
xxxx-registry-portus-nginx     ClusterIP  10.245.225.70   <none>       80/TCP             1s
xxxx-registry-portus           ClusterIP  10.245.135.72   <none>       3000/TCP           1s
xxxx-registry-portus-registry  ClusterIP  10.245.160.102  <none>       5000/TCP,5001/TCP  1s

NOTES:
1. Get the Portus URL:

  It may take a few moments for the Nginx proxy to find the Portus and Docker registry services, so you may get a 502 before connections are established.
  You can access Portus, and the private Docker registry through:
    https://docker-hub.xxxx.com:80

2. Create admin user account:

  You will be prompted to create an account before you can use Portus.
  In order to use the Docker registry without TLS you will need to setup the user with a specific name

  Username:
    Silly

  You can set the email and password to whatever you would like.

3. Associate Portus with the private Docker registry:

  After creating an admin account you will need to associate Portus with the installed instance of the Docker registry.

  You can give the registry whatever name you would like, but must fill out the rest of the credentials according to these instructions.

  Hostname:
    xxxx-registry-portus-registry:5000

  Click the button "Show Advanced"

  External Registry Name:
    https://xxxx.com:80

________

Arkas-MacBook-Pro:~ arka$ curl -vvL http://docker-hub.xxxx.com
* Rebuilt URL to: http://docker-hub.xxxx.com/
*   Trying 104.248.102.228...
* TCP_NODELAY set
* Connected to docker-hub.xxxx.com (104.248.102.228) port 80 (#0)
> GET / HTTP/1.1
> Host: docker-hub.xxxx.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.15.6
< Date: Thu, 03 Jan 2019 04:19:42 GMT
< Content-Type: text/html
< Content-Length: 171
< Connection: keep-alive
< Location: https://docker-hub.xxxx.com/
< 
* Ignoring the response-body
* Connection #0 to host docker-hub.xxxx.com left intact
* Issue another request to this URL: 'https://docker-hub.xxxx.com/'
*   Trying 104.248.102.228...
* TCP_NODELAY set
* Connected to docker-hub.xxxx.com (104.248.102.228) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.xxxx.com
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> GET / HTTP/1.1
> Host: docker-hub.xxxx.com
> User-Agent: curl/7.54.0
> Accept: */*
> 

Stays stuck there.
